server:
    port: 8081

management:
  server:
    port: 8085
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - camel
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    camel:
      enabled: true

gwh:
  service:
    profile: dispatcher
  framework:
    routes:
      load:
        params:
          enabled: true
    component:
      activemq:
        default:
          enabled: true
      kafka:
        default:
          enabled: true
      pgpencryption:
        enabled: true
      routemanagement:
        rest:
          enabled: true

  component:
    activemq:
      default:
        broker: tcp://192.168.6.1:61616
        username: artemis
        password: artemis
        session-cache-size: 10

    kafka:
      default:
        consumer:
          brokers: 192.168.6.1:29093
        producer:
          brokers: 192.168.6.1:29093

    pgp:
      default:
        publicKeyUserId: 'pw company <philip.waldorf@gmail.com>'
        publicKeyPassword: XXXXXXXX
        publicKeyFileName: 'file:/home/pwaldorf/.gnupg/pubring.gpg'
        privateKeyUserId: 'pw company <philip.waldorf@gmail.com>'
        privateKeyPassword: XXXXXXXX
        privateKeyFileName: 'file:/home/pwaldorf/.gnupg/secring.gpg'

  core:
    db:
      datasource:
        className: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.6.2:3306/gwh
        userName: root
        password: XXXXXXX
        minpoolsize: 0
        maxpoolsize: 50
        increment: 2
        maxidleTime: 300
        retryDelay: 600000
        jpa-dialect: org.hibernate.dialect.MySQLDialect
        jpa-ddl-auto: validate
        jpa-physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

camel:
  main:
    dev-console-enabled: true
  springboot:
    name: GWHDispatcher
   # tracing-standby: true
   # tracing: true
    dev-console-enabled: true

logging:
  level:
    org:
      apache:
        camel: INFO
      #springframework:
      #  transaction:
      #    interceptor: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
            BasicBinder: TRACE
      activemq:
        audit:
          base: DEBUG
          message: DEBUG