server:
    port: 8081

management:
  server:
    port: 8086
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - camel
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    camel:
      enabled: true

gwh:
  service:
    profile: dispatcher
    # profile: ftptestprofile
    # profile: ftptest2
    region: ALL
  properties:
    db:
      table: properties
      keyColumn: property_key
      valueColumn: property_value
      profileColumn: profile
      url: jdbc:mysql://192.168.6.2:3306/gwh
      userName: root
      password: ${GWH_CORE_DB_DATASOURCE_PASSWORD}

#   core:
#     db:
#       datasource:
#         className: com.mysql.cj.jdbc.Driver
#         url: jdbc:mysql://192.168.6.2:3306/gwh
#         userName: root
#         password: ${GWH_CORE_DB_DATASOURCE_PASSWORD}
#         minpoolsize: 0
#         maxpoolsize: 50
#         increment: 2
#         maxidleTime: 300
#         retryDelay: 600000
#         jpa-dialect: org.hibernate.dialect.MySQLDialect
#         jpa-ddl-auto: validate
#         jpa-physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# gwh:
#   service:
#     profile: dispatcher
#   framework:
#     routes:
#       load:
#         params:
#           enabled: true
#     component:
#       activemq:
#         default:
#           enabled: true
#       kafka:
#         default:
#           enabled: true
#       pgpencryption:
#         enabled: true
#       routemanagement:
#         rest:
#           enabled: true

#   component:
#     activemq:
#       default:
#         broker: tcp://192.168.6.1:61616
#         username: artemis
#         password: artemis
#         session-cache-size: 10

#     kafka:
#       default:
#         consumer:
#           brokers: 192.168.6.1:29093
#         producer:
#           brokers: 192.168.6.1:29093

#     pgp:
#       default:
#         publicKeyUserId: 'pw company <philip.waldorf@gmail.com>'
#         publicKeyPassword: ${GWH_CORE_DB_DATASOURCE_PASSWORD}
#         publicKeyFileName: 'file:/home/pwaldorf/.gnupg/pubring.gpg'
#         privateKeyUserId: 'pw company <philip.waldorf@gmail.com>'
#         privateKeyPassword: ${GWH_CORE_DB_DATASOURCE_PASSWORD}
#         privateKeyFileName: 'file:/home/pwaldorf/.gnupg/secring.gpg'

#   core:
#     db:
#       datasource:
#         className: com.mysql.cj.jdbc.Driver
#         url: jdbc:mysql://192.168.6.2:3306/gwh
#         userName: root
#         password: ${GWH_CORE_DB_DATASOURCE_PASSWORD}
#         minpoolsize: 0
#         maxpoolsize: 50
#         increment: 2
#         maxidleTime: 300
#         retryDelay: 600000
#         jpa-dialect: org.hibernate.dialect.MySQLDialect
#         jpa-ddl-auto: validate
#         jpa-physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

camel:
  servlet:
    mapping:
      context-path: /api/*
  main:
    dev-console-enabled: true
  springboot:
    name: GWH
   # tracing-standby: true
   # tracing: true
    dev-console-enabled: true

logging:
  level:
    org:
      apache:
        camel: INFO
        orm:
          jpa:
            JpaTransactionManager: ERROR
        kafka:
          transaction: ERROR
          listener:
            KafkaMessageListenerContainer: ERROR
        activemq:
          transaction: ERROR
      springframework:
       transaction:
         interceptor: ERROR

      # hibernate:
      #   SQL: DEBUG
      #   type:
      #     descriptor:
      #       sql:
      #       BasicBinder: TRACE
      # activemq:
      #   audit:
      #     base: DEBUG
      #     message: DEBUG