package com.pw.gwhparser.parser.enums;

public enum DataType {
    BIGDECIMAL, BIGDECIMAL_LIST, BOOLEAN, BOOLEAN_LIST, DATE, DATE_LIST, ENTITY, ENTITY_LIST, INTEGER, INTEGER_LIST, LONG, LONG_LIST,
    STRING, STRING_LIST, TIMESTAMP, TIMESTAMP_LIST
}
