server:
    port: 8081

management:
  server:
    port: 8085
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - camel      
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    camel:
      enabled: true

gtw:
  framework:
    routes:
      load:
        params:
          enabled: true
    component:
      jms:
        enabled: true
      kafka:
        enabled: true

camel:
  main:
    dev-console-enabled: true
  springboot:
    name: GWHDispatcher
   # tracing-standby: true
   # tracing: true    
    dev-console-enabled: true
                                 
    #routes-include-pattern: "classpath:camel/routeManagement/v1/*.yaml,\
    #                         classpath:camel/errorHandelers/v1/*.yaml,\
    #                         classpath:camel/routeConfigurations/v1/*.yaml,\
    #                         classpath:camel/routeTemplates/v1/*.yaml,\
    #                         classpath:camel/routes/dispatcher/v1/*.yaml,\
    #                         classpath:camel/testRoute/*.yaml"    
  servlet:
    mapping:
      context-path: /api/*
    
logging:
  level:
    org:
      apache:
        camel: INFO
      #springframework:
      #  transaction: 
      #    interceptor: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
            BasicBinder: TRACE