server:
    port: 8081

management:
  server:
    port: 8085
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - camel      
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    camel:
      enabled: true

gtw:
  framework:
    routes:
      load:
        params:
          enabled: true
    component:
      jms:
        enabled: true
      kafka:
        enabled: true

camel:
  main:
    dev-console-enabled: true
  springboot:
    name: GWHDispatcher    
    dev-console-enabled: true                       
  servlet:
    mapping:
      context-path: /api/*
    
logging:
  level:
    org:
      apache:
        camel: INFO
      #springframework:
      #  transaction: 
      #    interceptor: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
            BasicBinder: TRACE